import { Skills } from './skills'

export const SKILLLIST: Skills[] = [
    new Skills("Affinity Sliding", 1, 1),
    new Skills("Agitator", 5, 2),
    new Skills("Ammo Up", 3, 3),
    new Skills("Artillery", 3, 2),
    new Skills("Attack Boost", 7, 2),
    new Skills("Ballistics", 3, 2),
    new Skills("Blast Attack", 3, 2),
    new Skills("Blast Resistance", 3, 1),
    new Skills("Blight Resistance", 3, 2),
    new Skills("Bludgeoner", 3, 2),
    new Skills("Bombardier", 3, 1),
    new Skills("Botanist", 4, 1),
    new Skills("Bow Charge Plus", 1, 3),
    new Skills("Bubbly Dance", 3, 2),
    new Skills("Capture Master", 1, 3),
    new Skills("Carving Pro", 1, 1),
    new Skills("Chameleos Blessing", 4, 3),
    new Skills("Constitution", 5, 2),
    new Skills("Counterstrike", 3, 2),
    new Skills("Critical Boost", 3, 2),
    new Skills("Critical Draw", 2, 3),
    new Skills("Critical Element", 3, 2),
    new Skills("Critical Eye", 7, 2),
    new Skills("Defense Boost", 7, 1),
    new Skills("Diversion", 1, 1),
    new Skills("Divine Blessing", 3, 2),
    new Skills("Dragon Attack", 5, 3),
    new Skills("Dragon Resistance", 3, 1),
    new Skills("Dragonheart", 4, 3),
    new Skills("Earplugs", 5, 3),
    new Skills("Evade Extender", 3, 2),
    new Skills("Evade Window", 5, 2),
    new Skills("Fire Attack", 5, 3),
    new Skills("Fire Resistance", 3, 1),
    new Skills("Flinch Free", 3, 1),
    new Skills("Focus", 3, 2),
    new Skills("Fortify", 1, 2),
    new Skills("Free Meal", 3, 1),
    new Skills("Geologist", 3, 1),
    new Skills("Good Luck", 3, 3),
    new Skills("Guard", 5, 2),
    new Skills("Guard Up", 3, 2),
    new Skills("Handicraft", 5, 3),
    new Skills("Hellfire Cloak", 4, 3),
    new Skills("Heroics", 5, 2),
    new Skills("Horn Maestro", 1, 1),
    new Skills("Hunger Resistance", 3, 1),
    new Skills("Ice Attack", 5, 3),
    new Skills("Ice Resistance", 3, 1),
    new Skills("Item Prolonger", 3, 2),
    new Skills("Jump Master", 1, 3),
    new Skills("Kushala Blessing", 4, 3),
    new Skills("Latent Power", 5, 2),
    new Skills("Leap of Faith", 1, 1),
    new Skills("Load Shells", 2, 2),
    new Skills("Marathon Runner", 3, 2),
    new Skills("Master Mounter", 1, 2),
    new Skills("Master's Touch", 3, 2),
    new Skills("Maximum Might", 3, 2),
    new Skills("Mind's Eye", 3, 2),
    new Skills("Muck Resistance", 2, 1),
    new Skills("Mushroomancer", 3, 3),
    new Skills("Normal - Rapid Up", 3, 2),
    new Skills("Offensive Guard", 3, 3),
    new Skills("Paralysis Attack", 3, 2),
    new Skills("Paralysis Resistance", 3, 1),
    new Skills("Partbreaker", 3, 2),
    new Skills("Peak Performance", 3, 2),
    new Skills("Pierce Up", 3, 3),
    new Skills("Poison Attack", 3, 3),
    new Skills("Poison Resistance", 3, 1),
    new Skills("Power Prolonger", 3, 2),
    new Skills("Protective Polish", 3, 2),
    new Skills("Punishing Draw", 3, 2),
    new Skills("Quick Sheath", 3, 2),
    new Skills("Rapid Fire Up", 3, 3),
    new Skills("Rapid Morph", 3, 2),
    new Skills("Razor Sharp", 3, 2),
    new Skills("Recoil Down", 3, 1),
    new Skills("Recovery Speed", 3, 1),
    new Skills("Recovery Up", 3, 2),
    new Skills("Reload Speed", 3, 1),
    new Skills("Resentment", 3, 2),
    new Skills("Resuscitate", 3, 2),
    new Skills("Sleep Attack", 3, 2),
    new Skills("Sleep Resistance", 3, 1),
    new Skills("Slugger", 3, 2),
    new Skills("Spare Shot", 3, 2),
    new Skills("Special Ammo Boost", 2, 2),
    new Skills("Speed Eating", 3, 2),
    new Skills("Speed Sharpening", 3, 1),
    new Skills("Spread Up", 3, 3),
    new Skills("Stamina Surge", 3, 2),
    new Skills("Stamina Thief", 3, 1),
    new Skills("Steadiness", 2, 1),
    new Skills("Stormsoul", 5, 3),
    new Skills("Stun Resistance", 2, 1),
    new Skills("Teostra Blessing", 4, 3),
    new Skills("Thunder Alignment", 5, 3),
    new Skills("Thunder Attack", 5, 3),
    new Skills("Thunder Resistance", 3, 1),
    new Skills("Tremor Resistance", 3, 2),
    new Skills("Wall Runner", 3, 2),
    new Skills("Water Attack", 3, 3),
    new Skills("Water Resistance", 3, 1),
    new Skills("Weakness Exploit", 3, 2),
    new Skills("Wide-Range", 5, 2),
    new Skills("Wind Alignment", 5, 3),
    new Skills("Windproof", 3, 1),
    new Skills("Wirebug Whisperer", 3, 2),
];