import { Skill } from './Skill'

export const SKILL_LIST: Skill[] = [
    new Skill(1, "Affinity Sliding", 1, 1),
    new Skill(2, "Agitator", 5, 2),
    new Skill(3, "Ammo Up", 3, 3),
    new Skill(4, "Artillery", 3, 2),
    new Skill(5, "Attack Boost", 7, 2),
    new Skill(6, "Ballistics", 3, 2),
    new Skill(7, "Blast Attack", 3, 2),
    new Skill(8, "Blast Resistance", 3, 1),
    new Skill(9, "Blight Resistance", 3, 2),
    new Skill(10, "Bludgeoner", 3, 2),
    new Skill(11, "Bombardier", 3, 1),
    new Skill(12, "Botanist", 4, 1),
    new Skill(13, "Bow Charge Plus", 1, 3),
    new Skill(14, "Bubbly Dance", 3, 2),
    new Skill(15, "Capture Master", 1, 3),
    new Skill(16, "Carving Pro", 1, 1),
    new Skill(17, "Chameleos Blessing", 4, 3),
    new Skill(18, "Constitution", 5, 2),
    new Skill(19, "Counterstrike", 3, 2),
    new Skill(20, "Critical Boost", 3, 2),
    new Skill(21, "Critical Draw", 3, 2),
    new Skill(22, "Critical Element", 3, 2),
    new Skill(23, "Critical Eye", 7, 2),
    new Skill(24, "Defense Boost", 7, 1),
    new Skill(25, "Diversion", 1, 1),
    new Skill(26, "Divine Blessing", 3, 2),
    new Skill(27, "Dragon Attack", 5, 3),
    new Skill(28, "Dragon Resistance", 3, 1),
    new Skill(29, "Dragonheart", 4, 3),
    new Skill(30, "Earplugs", 5, 3),
    new Skill(31, "Evade Extender", 3, 2),
    new Skill(32, "Evade Window", 5, 2),
    new Skill(33, "Fire Attack", 5, 3),
    new Skill(34, "Fire Resistance", 3, 1),
    new Skill(35, "Flinch Free", 3, 1),
    new Skill(36, "Focus", 3, 2),
    new Skill(37, "Fortify", 1, 2),
    new Skill(38, "Free Meal", 3, 1),
    new Skill(39, "Geologist", 3, 1),
    new Skill(40, "Good Luck", 3, 3),
    new Skill(41, "Guard", 5, 2),
    new Skill(42, "Guard Up", 3, 2),
    new Skill(43, "Handicraft", 5, 3),
    new Skill(44, "Hellfire Cloak", 4, 3),
    new Skill(45, "Heroics", 5, 2),
    new Skill(46, "Horn Maestro", 1, 1),
    new Skill(47, "Hunger Resistance", 3, 1),
    new Skill(48, "Ice Attack", 5, 3),
    new Skill(49, "Ice Resistance", 3, 1),
    new Skill(50, "Item Prolonger", 3, 2),
    new Skill(51, "Jump Master", 1, 3),
    new Skill(52, "Kushala Blessing", 4, 3),
    new Skill(53, "Latent Power", 5, 2),
    new Skill(54, "Leap of Faith", 1, 1),
    new Skill(55, "Load Shells", 2, 2),
    new Skill(56, "Marathon Runner", 3, 2),
    new Skill(57, "Master Mounter", 1, 2),
    new Skill(58, "Master's Touch", 3, 2),
    new Skill(59, "Maximum Might", 3, 2),
    new Skill(60, "Mind's Eye", 3, 2),
    new Skill(61, "Muck Resistance", 2, 1),
    new Skill(62, "Mushroomancer", 3, 3),
    new Skill(63, "Normal - Rapid Up", 3, 2),
    new Skill(64, "Offensive Guard", 3, 3),
    new Skill(65, "Paralysis Attack", 3, 2),
    new Skill(66, "Paralysis Resistance", 3, 1),
    new Skill(67, "Partbreaker", 3, 2),
    new Skill(68, "Peak Performance", 3, 2),
    new Skill(69, "Pierce Up", 3, 3),
    new Skill(70, "Poison Attack", 3, 3),
    new Skill(71, "Poison Resistance", 3, 1),
    new Skill(72, "Power Prolonger", 3, 2),
    new Skill(73, "Protective Polish", 3, 2),
    new Skill(74, "Punishing Draw", 3, 2),
    new Skill(75, "Quick Sheath", 3, 2),
    new Skill(76, "Rapid Fire Up", 3, 3),
    new Skill(77, "Rapid Morph", 3, 2),
    new Skill(78, "Razor Sharp", 3, 2),
    new Skill(79, "Recoil Down", 3, 1),
    new Skill(80, "Recovery Speed", 3, 1),
    new Skill(81, "Recovery Up", 3, 2),
    new Skill(82, "Reload Speed", 3, 1),
    new Skill(83, "Resentment", 3, 2),
    new Skill(84, "Resuscitate", 3, 2),
    new Skill(85, "Sleep Attack", 3, 2),
    new Skill(86, "Sleep Resistance", 3, 1),
    new Skill(87, "Slugger", 3, 2),
    new Skill(88, "Spare Shot", 3, 2),
    new Skill(89, "Special Ammo Boost", 2, 2),
    new Skill(90, "Speed Eating", 3, 2),
    new Skill(91, "Speed Sharpening", 3, 1),
    new Skill(92, "Spread Up", 3, 3),
    new Skill(93, "Stamina Surge", 3, 2),
    new Skill(94, "Stamina Thief", 3, 1),
    new Skill(95, "Steadiness", 2, 1),
    new Skill(96, "Stormsoul", 5, 3),
    new Skill(97, "Stun Resistance", 2, 1),
    new Skill(98, "Teostra Blessing", 4, 3),
    new Skill(99, "Thunder Alignment", 5, 3),
    new Skill(100, "Thunder Attack", 5, 3),
    new Skill(101, "Thunder Resistance", 3, 1),
    new Skill(102, "Tremor Resistance", 3, 2),
    new Skill(103, "Wall Runner", 3, 2),
    new Skill(104, "Water Attack", 3, 3),
    new Skill(105, "Water Resistance", 3, 1),
    new Skill(106, "Weakness Exploit", 3, 2),
    new Skill(107, "Wide-Range", 5, 2),
    new Skill(108, "Wind Alignment", 5, 3),
    new Skill(109, "Windproof", 3, 1),
    new Skill(110, "Wirebug Whisperer", 3, 2)
];